import type { Palette } from "../palette";
import { STEPS } from "../scale";

export interface ScssOptions {
  /** Variable prefix: `color` gives `$color-brand-500`. Default none: `$brand-500`. */
  prefix?: string;
}

/**
 * Sass variables with hex values: `$brand-500` for light mode,
 * `$brand-500-dark` for dark mode, `$brand-on-500` for the text color.
 * For projects without CSS custom properties; prefer `toCss` otherwise.
 */
export function toScss(palette: Palette, options: ScssOptions = {}): string {
  const p = options.prefix ? `${options.prefix}-` : "";
  const lines = ["// Generated by @sweberdev/gradient."];
  for (const scale of palette.scales) {
    lines.push("");
    for (const mode of ["light", "dark"] as const) {
      const suffix = mode === "dark" ? "-dark" : "";
      for (const step of STEPS) {
        lines.push(`$${p}${scale.name}-${step}${suffix}: ${scale[mode][step].hex};`);
      }
      for (const step of STEPS) {
        lines.push(`$${p}${scale.name}-on-${step}${suffix}: ${scale[mode][step].on};`);
      }
    }
  }
  return `${lines.join("\n")}\n`;
}

/**
 * A TypeScript module with the palette as a typed constant, for CSS-in-JS,
 * React Native or charts: `colors.brand.light[600]`, `colors.brand.light.on[600]`.
 */
export function toTypeScript(palette: Palette): string {
  const tree: Record<string, Record<string, Record<string, unknown>>> = {};
  for (const scale of palette.scales) {
    const entry: Record<string, Record<string, unknown>> = {};
    for (const mode of ["light", "dark"] as const) {
      const steps: Record<string, unknown> = {};
      const on: Record<string, string> = {};
      for (const step of STEPS) {
        steps[step] = scale[mode][step].hex;
        on[step] = scale[mode][step].on;
      }
      steps.on = on;
      entry[mode] = steps;
    }
    tree[scale.name] = entry;
  }
  return [
    "// Generated by @sweberdev/gradient.",
    `export const colors = ${JSON.stringify(tree, null, 2)} as const;`,
    "",
    "export type ColorName = keyof typeof colors;",
    'export type ColorStep = Exclude<keyof (typeof colors)[ColorName]["light"], "on">;',
    "",
  ].join("\n");
}
