import { formatOklch, fromHex } from "../color";
import type { Palette } from "../palette";
import { generateNeutral, generateScale, type Mode, type Scale } from "../scale";
import { createSeries } from "../series";
import { statusColors } from "../status";
import { block, type CssOptions, darkBlocks, lightDarkDeclarations, schemeBlocks } from "./css";

export interface ShadcnOptions extends Pick<CssOptions, "dark" | "darkSelector" | "lightSelector"> {
  /** `oklch` (default, shadcn/ui with Tailwind v4) or `hex`. */
  format?: "oklch" | "hex";
  /** Adds the `@theme inline` block that maps the variables to Tailwind colors. Default true. */
  theme?: boolean;
}

export type ShadcnTokens = Record<string, string>;

const NAMES = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "border",
  "input",
  "ring",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
] as const;

/**
 * The semantic colors of shadcn/ui as hex, per mode, picked from the palette
 * so that the contrast promises hold:
 *
 * - `foreground` and `card-foreground` on `background` and `card`: at least 7:1
 * - `primary-foreground`, `secondary-foreground`, `accent-foreground`,
 *   `muted-foreground` and `destructive-foreground` on their backgrounds: at least 4.5:1
 * - `input` (the border of form fields) and `ring`: at least 3:1 on the page
 *
 * Needs the scales `brand` (or the first color you passed) and `neutral`.
 * `danger` is derived from the brand when the palette has none.
 */
export function shadcnTokens(palette: Palette): Record<Mode, ShadcnTokens> {
  const brand = palette.scales.find((s) => s.name === "brand") ?? palette.scales[0];
  if (!brand) throw new Error("toShadcn needs a palette with at least one color.");
  const neutral: Scale =
    palette.scales.find((s) => s.name === "neutral") ?? generateNeutral(brand.source);
  const danger: Scale =
    palette.scales.find((s) => s.name === "danger") ??
    generateScale(statusColors(brand.source).danger, { name: "danger" });
  const series = createSeries(brand.source, { count: 5 });

  const out = {} as Record<Mode, ShadcnTokens>;
  for (const mode of ["light", "dark"] as const) {
    const n = neutral[mode];
    const b = brand[mode];
    const d = danger[mode];
    const card = mode === "light" ? "#ffffff" : n[100].hex;
    const tokens: ShadcnTokens = {
      background: n[50].hex,
      foreground: n[900].hex,
      card,
      "card-foreground": n[900].hex,
      popover: card,
      "popover-foreground": n[900].hex,
      primary: b[600].hex,
      "primary-foreground": b[600].on,
      secondary: n[100].hex,
      "secondary-foreground": n[900].hex,
      muted: n[100].hex,
      "muted-foreground": n[700].hex,
      accent: b[100].hex,
      "accent-foreground": b[900].hex,
      destructive: d[600].hex,
      "destructive-foreground": d[600].on,
      border: n[200].hex,
      input: n[500].hex,
      ring: b[500].hex,
    };
    series[mode].slice(0, 5).forEach((hex, i) => {
      tokens[`chart-${i + 1}`] = hex;
    });
    out[mode] = tokens;
  }
  return out;
}

/**
 * Stylesheet for shadcn/ui: the variables in `:root` and `.dark`, and the
 * `@theme inline` mapping for Tailwind v4. Paste it over the theme in your
 * `globals.css`. Dark mode defaults to the `.dark` class, as in shadcn/ui.
 */
export function toShadcn(palette: Palette, options: ShadcnOptions = {}): string {
  const tokens = shadcnTokens(palette);
  const format = options.format ?? "oklch";
  const css: CssOptions = { dark: options.dark ?? "class" };
  if (options.darkSelector) css.darkSelector = options.darkSelector;
  if (options.lightSelector) css.lightSelector = options.lightSelector;
  const lines = (mode: Mode) =>
    NAMES.map((name) => {
      const hex = tokens[mode][name] as string;
      return `--${name}: ${format === "hex" ? hex : formatOklch(fromHex(hex))};`;
    });

  const parts: string[] = [];
  if (css.dark === "light-dark") {
    parts.push(
      block(":root", [
        "color-scheme: light dark;",
        ...lightDarkDeclarations(lines("light"), lines("dark")),
      ]),
    );
    parts.push(...schemeBlocks(css));
  } else {
    parts.push(block(":root", lines("light")));
    parts.push(...darkBlocks(lines("dark"), css));
  }
  if (options.theme !== false) {
    parts.push(
      block(
        "@theme inline",
        NAMES.map((n) => `--color-${n}: var(--${n});`),
      ),
    );
  }
  return `/* Generated by @sweberdev/gradient. shadcn/ui theme. */\n${parts.join("\n\n")}\n`;
}
